import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import AuthProvider from '@/helpers/AuthProvider'

export const metadata: Metadata = {
  title: "Anonymous Feedback",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <AuthProvider>
        <Navbar />
        <div>
          {children}
        </div>
      </AuthProvider>
  );
}